config/routes.rb
AssetTrackerThree::Application.routes.draw do |map|
  resources :clients

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  respond_to :html, :xml

  # GET /clients
  # GET /clients.xml
  def index
    @clients = Client.all

    respond_with @clients
  end

  # GET /clients/1
  # GET /clients/1.xml
  def show
    @client = Client.find(params[:id])

    respond_with @client
  end

  # GET /clients/new
  # GET /clients/new.xml
  def new
    @client = Client.new

    respond_with @client
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])

    respond_with @client
  end

  # POST /clients
  # POST /clients.xml
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to(@client, :notice => 'Client was successfully created.') }
        format.xml  { render :xml => @client, :status => :created, :location => @client }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.xml
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to(@client, :notice => 'Client was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.xml
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to(clients_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bill_rate %><br />
    <%= f.text_field :bill_rate %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Bill rate</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.bill_rate %></td>
    <td><%= client.status %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Bill rate:</b>
  <%= @client.bill_rate %>
</p>

<p>
  <b>Status:</b>
  <%= @client.status %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AssetTrackerThree</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>